/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiJobsIndexRouteImport } from './routes/api/jobs/index'
import { Route as ApiJobsJobIdRouteImport } from './routes/api/jobs/$jobId'
import { Route as ApiJobsJobIdDownloadRouteImport } from './routes/api/jobs/$jobId.download'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIndexRoute = ApiJobsIndexRouteImport.update({
  id: '/api/jobs/',
  path: '/api/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsJobIdRoute = ApiJobsJobIdRouteImport.update({
  id: '/api/jobs/$jobId',
  path: '/api/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsJobIdDownloadRoute = ApiJobsJobIdDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => ApiJobsJobIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/jobs/$jobId': typeof ApiJobsJobIdRouteWithChildren
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/jobs/$jobId/download': typeof ApiJobsJobIdDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/jobs/$jobId': typeof ApiJobsJobIdRouteWithChildren
  '/api/jobs': typeof ApiJobsIndexRoute
  '/api/jobs/$jobId/download': typeof ApiJobsJobIdDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/jobs/$jobId': typeof ApiJobsJobIdRouteWithChildren
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/jobs/$jobId/download': typeof ApiJobsJobIdDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/jobs/$jobId' | '/api/jobs/' | '/api/jobs/$jobId/download'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/jobs/$jobId' | '/api/jobs' | '/api/jobs/$jobId/download'
  id:
    | '__root__'
    | '/'
    | '/api/jobs/$jobId'
    | '/api/jobs/'
    | '/api/jobs/$jobId/download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiJobsJobIdRoute: typeof ApiJobsJobIdRouteWithChildren
  ApiJobsIndexRoute: typeof ApiJobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/': {
      id: '/api/jobs/'
      path: '/api/jobs'
      fullPath: '/api/jobs/'
      preLoaderRoute: typeof ApiJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$jobId': {
      id: '/api/jobs/$jobId'
      path: '/api/jobs/$jobId'
      fullPath: '/api/jobs/$jobId'
      preLoaderRoute: typeof ApiJobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$jobId/download': {
      id: '/api/jobs/$jobId/download'
      path: '/download'
      fullPath: '/api/jobs/$jobId/download'
      preLoaderRoute: typeof ApiJobsJobIdDownloadRouteImport
      parentRoute: typeof ApiJobsJobIdRoute
    }
  }
}

interface ApiJobsJobIdRouteChildren {
  ApiJobsJobIdDownloadRoute: typeof ApiJobsJobIdDownloadRoute
}

const ApiJobsJobIdRouteChildren: ApiJobsJobIdRouteChildren = {
  ApiJobsJobIdDownloadRoute: ApiJobsJobIdDownloadRoute,
}

const ApiJobsJobIdRouteWithChildren = ApiJobsJobIdRoute._addFileChildren(
  ApiJobsJobIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiJobsJobIdRoute: ApiJobsJobIdRouteWithChildren,
  ApiJobsIndexRoute: ApiJobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
